### ISSUE TITLE
no print() being used

### ISSUE THREAD

**Issue by Mato52** [Sturzgefahr/ThinkPython#1]
Why is print() not being used in the corrections featured here? [https://github.com/Sturzgefahr/ThinkPython/edit/master/Think%20Python%20-%20Chapter%2001/Think%20Python%20-%20Chapter%2001.ipynb](https://github.com/Sturzgefahr/ThinkPython/edit/master/Think%20Python%20-%20Chapter%2001/Think%20Python%20-%20Chapter%2001.ipynb) Am I missing something?

**Comment by STRZGR** [comment]
Hi,

Which exercise in particular are you referring to?

`print()` is only used when outputting strings.  You wouldn’t need it for the result of a mathematical expression.

In an actual function/program, you would definitely use `print()` to show the result of a mathematical expression.  I believe the author just wanted to show that Python *could* be used as a calculator, even if in practice it rarely is.

Also, if you have question like this, just message me directly.  You would only need to open an issue if there was an issue in my code that needed to be addressed.

Cheers
